microlly/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('microlly_review.urls')),
    path('microlly_review/', include('microlly_review.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

microlly_review/urls.py
from django.urls import path
from microlly_review import views

app_name = 'microlly_review'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('', views.index, name='index'),
    path('plus/<slug:slug>/<int:pk>', views.plus, name='plus'),
    path('edit/<slug:slug>/<int:pk>', views.edition_post, name='edition'),
    path('delete/<slug:slug>/<int:pk>', views.delete, name='delete'),
    path('create/', views.creation_post, name='creation'),
    path('post_user/<str:author>',
         views.post_list, name='post_list'),
    
]

microlly_review/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.auth import login, logout



class Post_Plus(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField(default='a-slug')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def preview(self):
        return self.body[:100]+'...'

    def _get_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post_Plus.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self._get_slug()
        super().save(*args, **kwargs)

    class Meta():
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

microlly_review/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from microlly_review import models

class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=100, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2', )


class Creation(forms.ModelForm):
    class Meta:
        model = models.Post_Plus
        fields = ['title', 'body']


class Edition(forms.ModelForm):
    class Meta:
        model = models.Post_Plus
        fields = ['title', 'body']

microlly_review/views.py
from django.shortcuts import render, get_object_or_404, redirect
from microlly_review.models import Post_Plus
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from microlly_review import forms
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout


def sign_up(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('microlly_review:index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def log_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('microlly_review:index')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def log_out(request):
    if request.method == 'POST':
        logout(request)
        return redirect('microlly_review:index')
    else:
        return redirect('microlly_review:index')


def index(request):
    posts_list = Post_Plus.objects.all().order_by('-post_date')
    paginator = Paginator(posts_list, 9)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'index.html', {'last_posts': posts})


def plus(request, slug, pk):
    post = get_object_or_404(Post_Plus, slug=slug, pk=pk)
    return render(request, 'plus.html', {'post': post})

def post_list(request, author):

    author = get_object_or_404(User, username=author)
    posts_list = Post_Plus.objects.filter(author=author)
    print(posts_list)
    paginator = Paginator(posts_list, 9)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        "author": author,
        "list_posts_user": posts,
    }
    return render(request, 'post_list.html', context)


def delete(request, slug, pk):
    post = get_object_or_404(Post_Plus, pk=pk)
    if request.user != post.author:
        return redirect('microlly_review:index')
    if request.method == 'POST':
        post.delete()
        return redirect('microlly_review:index')
    return render(request, 'login.html')

@login_required(login_url="/microlly_review/login/")
def creation_post(request):
    if request.method == 'POST':
        form = forms.Creation(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('microlly_review:index')
    else:
        form = forms.Creation()
    return render(request, 'creation_post.html', {'form': form})


@login_required(login_url="/microlly_review/login/")
def edition_post(request, slug, pk):
    post = get_object_or_404(Post_Plus, slug=slug, pk=pk)
    form = forms.Edition(request.POST or None, instance=post)
    if request.user != post.author:
        return redirect('microlly_review:index')
    if request.method == 'POST':
        if form.is_valid():
            post.save()
            return redirect('microlly_review:index')
    context = {
        "form": form,
        "post": post,
    }
    return render(request, 'edition_post.html', context)

microlly_review/templates/_base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style.css' %}" />
    <title>Microlly</title>
</head>

<body>
    <header class="banner">
            <nav class="navbar navbar-expand-sm color1 navbar-light fixed-top ">
                <div class="collapse navbar-collapse" id="navDropdown">
                    <ul class="navbar-nav mx-5">
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-1">
                            <form class="form-inline" action="{% url 'microlly_review:index' %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-outline-light" type="submit">ACCUEIL</button>
                            </form>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item mx-1">
                            <form class="form-inline" action="{% url 'microlly_review:creation' %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-outline-light" type="submit">NOUVEAU</button>
                            </form>
                        </li>
                        <li class="nav-item mx-1">
                            <form class="form-inline" action="{% url 'microlly_review:logout' %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-outline-light" type="submit">LOGOUT</button>
                            </form>
                        </li>
                        {% else %}
                        <li class="nav-item mx-1">
                            <form class="form-inline" action="{% url 'microlly_review:login' %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-outline-light" type="submit">LOGIN</button>
                            </form>
                        </li>
                        <li class="nav-item mx-1">
                            <form class="form-inline" action="{% url 'microlly_review:signup' %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-outline-light" type="submit">REGISTER</button>
                            </form>
                        </li>
                        {% endif %}
                        {% if user.is_superuser %}
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-4">
                        </li>
                        <li class="nav-item mx-2">
                        </li>
                        <li class="nav-item mx-1">
                            <a class="btn btn-outline-light" href="/admin">ADMIN</a>
                        </li>
                        {% endif%}
                    </ul>
                </div>
            </nav>
        <div class="marge">
        </div>
    </header>

    <section class="main-section">
        <div class="marge">
        <header class="container-fluid header-section d-flex align-items-center color2">
            <div class="container d-flex justify-content-between align-items-center">
                <div class="order-1 ">
                    <h3 class="d-inline text-white">
                        {% block section-title %}
                        {% endblock %}
                    </h3>
                </div>
            </div>
        </header>
        </div>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </section>

    <footer class="footer align-middle color1">
        <div class="container">
            <p class="text-center color3 ">Microlly Apps</p>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

microlly_review/templates/creation_post.html
{% extends '_base.html' %}

{% block section-title %}
Bienvenue sur Microlly: Creating post
{% endblock %}

{% block content %}
    <form class="d-flex flex-column" action="{% url 'microlly_review:creation' %}" method="POST">
        {% csrf_token %}
        {% include 'form.html' with form=form %}
        <input type="submit" class="btn btn-dark" value="Create">
    </form>
{% endblock %}

microlly_review/templates/edition_post.html
{% extends '_base.html' %}

{% block section-title %}
Bienvenue sur Microlly: Editing post
{% endblock %}

{% block content %}
    <form class="d-flex flex-column" action="{% url 'microlly_review:edition' post.slug post.pk %}" method="POST">
        {% csrf_token %}
        {% include 'form.html' with form=form %}
        <input type="submit" class="btn btn-dark" value="Edit">
    </form>
{% endblock %}

microlly_review/templates/form.html
<!--{% load widget_tweaks %}-->

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="form-group">
    {{ field.label_tag }}
    {% if form.is_bound %}
        {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
            {% endfor %}
        {% else %}
            {% render_field field class="form-control is-valid" %}
        {% endif %}
    {% else %}
        {% render_field field class="form-control" %}
    {% endif %}
    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
</div>
{% endfor %}

microlly_review/templates/index.html
{% extends '_base.html' %}

{% block section-title %}
Bienvenue sur Microlly: Last posts
{% endblock %}

{% block content %}
{% if last_posts %}
<article class="row">
    {% for post in last_posts %}
    <div class="card-container col-md-6 col-lg-4">
        <div class="card border border-lightgreen mb-3">
            <div class="card-body">
                <h4 class="card-title">
                    <a class="badge color4" href="{% url 'microlly_review:plus' post.slug post.pk %}">
                        {{ post.title }}</a>
                </h4>
                <p class="card-text">
                    {{post.preview}}
                </p>
            </div>
            <div class="card-footer">
                <p class="card-text">
                    <small class="text-muted">
                        Posted by: <a href="{% url 'microlly_review:post_list' post.author %}">{{post.author}}</a>
                    </small>
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        Create: {{post.post_date}}
                    </small>
                </p>
                
            </div>
        </div>
    </div>
    {% endfor %}
</article>

<nav aria-label="Pagination author posts">
    <ul class="pagination justify-content-center">
        {% if last_posts.has_previous %}
        <li class="page-item"> <a class="page-link color3" href="?page=1">&laquo; first</a> </li>
        <li class="page-item"><a class="page-link color3" href="?page={{ last_posts.previous_page_number }}">previous</a></li>
        {% endif %}
        {% if last_posts.has_next %}
        <li class="page-item"><a class="page-link color3" href="?page={{ last_posts.next_page_number }}">next</a></li>
        <li class="page-item"><a class="page-link color3" href="?page={{ last_posts.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

{% else %}
<p>Aucunes publications.</p>
{% endif %}
{% endblock %}

microlly_review/templates/login.html
{% extends '_base.html' %}

{% block section-title %}
Bienvenue sur Microlly: Login
{% endblock %}

{% block content %}
<form class="d-flex flex-column" action="{% url 'microlly_review:login' %}" method="POST">
    {% csrf_token %}
    {% include 'form.html' with form=form %}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" class="btn btn-dark" value="Login">
</form>
{% endblock %}

microlly_review/templates/plus.html
{% extends '_base.html' %}

{% block section-title %}
Bienvenue sur Microlly: Plus
{% endblock %}

{% block content %}
<h4>{{ post.title }}</h4>
<p>{{ post.body }}</p>
<p>Create: {{ post.post_date }}</p>
<p>Edit: {{ post.edit_date }}</p>

{% if user.is_authenticated %}
<div class="container d-flex flex-column justify-content-center">
    <form class="my-1" action="{% url 'microlly_review:edition' post.slug post.pk %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark w-100" type="submit">Edit</button>
    </form>
    <form class="my-1" action="{% url 'microlly_review:delete' post.slug post.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark w-100" type="submit">Delete</button>
    </form>
</div>
{% endif %}

{% endblock %}

microlly_review/templates/post_list.html
{% extends '_base.html' %}

{% block section-title %}
Bienvenue sur Microlly: Post by: {{author}}
{% endblock %}

{% block content %}
<article class="row">
    {% for post in post_list %}
    <div class="card-container col-md-6 col-lg-4">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    <a class="badge color4" href="{% url 'microlly_review:plus' post.slug post.pk %}">
                        {{ post.title }}</a>
                </h4>
                <p class="card-text">
                    {{post.preview}}
                </p>
            </div>
            <div class="card-footer">
                <p class="card-text">
                    <small class="text-muted">
                        Posted by: <a href="{% url 'microlly_review:list_post_user' post.author %}">{{post.author}}</a>
                        <span class="text-dark"></span>
                        on {{post.release_date}}
                    </small>
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        Last update: {{post.edit_date}}
                    </small>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</article>

<nav aria-label="Pagination author posts">
    <ul class="pagination justify-content-center">
        {% if list_posts_user.has_previous %}
        <li class="page-item"> <a class="page-link color3" href="?page=1">&laquo; first</a> </li>
        <li class="page-item"><a class="page-link color3" href="?page={{ list_posts_user.previous_page_number }}">previous</a></li>
        {% endif %}
        {% if list_posts_user.has_next %}
        <li class="page-item"><a class="page-link color3" href="?page={{ list_posts_user.next_page_number }}">next</a></li>
        <li class="page-item"><a class="page-link color3" href="?page={{ list_posts_user.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

microlly_review/templates/signup.html
{% extends '_base.html' %}

{% block section-title %}
Bienvenue sur Microlly: Sign up
{% endblock %}



{% block content %}
<form class="d-flex flex-column" action="{% url 'microlly_review:signup' %}" method="POST">
    {% csrf_token %}
    {% include 'form.html' with form=form %}
    <input type="submit" class="btn btn-dark" value="Signup">
</form>
{% endblock %}